version: '3.6'
services:
  reportserver:
    build:
      context: reportserver
      dockerfile: Dockerfile
  iris:
    build: 
      context: iris
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 32791:52773
      - 53773
    volumes:
      - ./:/irisdev/app